/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "build_time:20240306153454 commit:788fa78"
#endif /* AVUTIL_FFVERSION_H */
