/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "build_time:20250509094718 commit:224071b"
#endif /* AVUTIL_FFVERSION_H */
