/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "build_time:20231124144741 commit:7b9f43d"
#endif /* AVUTIL_FFVERSION_H */
